### PR TITLE
Added support of constrainOnly flag

### PR DESCRIPTION
**Pull request by ihor-sviziev**
constrainOnly method doing following: Guarantee, that image picture will not be bigger, than it was. Applicable before calling resize() It is false by default

### CODE REVIEW

**Review by LeeSaferite — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@LeeSaferite Could you merge these changes & add new release for that?

**Comment by ihor-sviziev** [comment]
@drobinson  could you create release tag with these changes?

**Comment by drobinson** [comment]
Sure here you go - sorry for the delay https://github.com/AOEpeople/Aoe_LazyCatalogImages/releases/tag/1.0.2

**Comment by LeeSaferite** [comment]
@drobinson You tagged the code, but didn't update the package version in the config XML.

**Comment by drobinson** [comment]
@LeeSaferite DARN, well I'm not sure it's worth creating a new tag/updating this one just to keep the config.xml in sync with the release version, especially if there weren't any setup scripts included...thoughts?

**Comment by LeeSaferite** [comment]
It's fine. Just something to be aware of for the future.

**Pull request merged**
