### PR TITLE
Reduce filename length further, support legacy filenames

### PR DESCRIPTION
**Pull request by toddbc**
We have some saved JSON-encoded file paths, so it's more convenient if they just continue working, but I can't be sure they've all been generated.

This also reduces the filename length by another 15% or so in the common case.  JSON compresses relatively well.

All 3 variants of the filenames (before 722e8a1a, after 722e8a1a, and with ZLIB) work / are supported for decode.

### CODE REVIEW

**Comment by drobinson** [comment]
Looks good but I'm not well versed in this module.  Maybe @thebod or @LeeSaferite can weigh in...

**Comment by toddbc** [comment]
Oh, forgot to note why it matters: filenames longer than 255 characters will generate a "filename too long" error, i.e. when hosted on NFS.

Mostly this is impacted by the source filename length, which is part of the encoded JSON.

**Comment by LeeSaferite** [comment]
I think I would ask why you are hosting ephemeral cache files on NFS though. :)  One of the primary goals behind this module was to remove the need to host the cached images on NFS for cluster sharing. Since the request is lossless, the URL contains all that is needed to create the image. Each node of a cluster can then rebuild the image the first time it sees the URL.

**Comment by LeeSaferite** [comment]
I also would highly prefer this new feature be behind a feature flag if possible @drobinson

**Comment by toddbc** [comment]
Fair, but it's definitely easier (and extremely common) to host all of media/ on NFS.

Not that it matters since the limit for most other filesystems is also 255.

**Comment by drobinson** [comment]
Good point re feature flag - are you interested in doing that to get this merged @toddbc ?

**Comment by toddbc** [comment]
I can add that - won't have time until later to verify it.  Are you looking for one feature flag, or two (re-enabling support for the syntax pre- 722e8a1a that didn't have a feature flag, and for compression)?

**Comment by toddbc** [comment]
I haven't been spending much time on Magento 1 lately.  I can update this, but I want to avoid too much back and forth that I may not have time for.

Would just the one feature flag be okay?

**Comment by LeeSaferite** [comment]
Talk about a blast from the past. Sorry for this one just hanging out @toddbc

**Pull request closed without merging**
