### PR TITLE
Added missing files (lci.php and media .htaccess) to composer.json map

### PR DESCRIPTION
**Pull request by erfanimani**

### CODE REVIEW

**Comment by erfanimani** [comment]
Ah didn't see there was another PR with the same fix. Ignore this one..

**Comment by ihor-sviziev** [comment]
It's duplicate of #14. I think it should be closed

**Comment by LeeSaferite** [comment]
I merged the previous fix instead. Thanks for the PR though.

**Comment by erfanimani** [comment]
Cool. np

**Pull request closed without merging**
